apiVersion: v1
kind: Service
metadata:
  name: jellyfin-service
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.loadBalancerIP }}
  ports:
  - name: web
    port: 80
    targetPort: 8096
  selector:
    app: jellyfin
