apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-tubearchivist
spec:
  selector:
    app: tubearchivist
  type: LoadBalancer
  loadBalancerIP: {{ .Values.loadBalancerIP }}
  ports:
  - name: web
    port: 80
    targetPort: 8000
