apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.loadBalancerIP }}
  ports:
  - name: http-service
    port: 8086
    targetPort: 8086
  selector:
    app: influxdb
