apiVersion: v1
kind: Service
metadata:
  name: navidrome-service
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.loadBalancerIP }}
  ports:
  - name: http
    port: 80
    targetPort: 4533
  selector:
    app: navidrome
