apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  selector:
    matchLabels:
      app: jenkins
  replicas: {{ index .Values "replicaCount" }}
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      volumes:
      - name: jenkins-persistent
        nfs:
          server: {{ .Values.nfs.nfsMediaServerAddress }}
          path: {{ .Values.nfs.nfsMountPath }}
      containers:
      - name: jenkins
        image: jenkins/jenkins
        env:
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 50000
          protocol: TCP
        - containerPort: 50000
          protocol: UDP
        volumeMounts:
        - name: jenkins-persistent
          mountPath: "/var/jenkins_home"
