apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinchflat
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: pinchflat
  template:
    metadata:
      labels:
        app: pinchflat
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - kube-1
      containers:
      - name: pinchflat
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
        #- name: TZ
        #  value: Asia/Shanghai
        ports:
        - name: http
          containerPort: 8945
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /config
        - name: downloads
          mountPath: /downloads
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: pvc-config
      - name: downloads
        nfs:
          server: {{ .Values.nfs.nfsMediaServerAddress }}
          path: {{ .Values.nfs.nfsDownloadsMountPath}}
