apiVersion: v1
kind: Service
metadata:
  name: pinchflat-service
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.loadBalancerIP }}
  ports:
  - name: http
    port: 80
    targetPort: 8945
  selector:
    app: pinchflat
