apiVersion: v1
data:
  UMASK_SET: "022"
  TZ: "Asia/Shanghai"
  RPC_PORT: {{ quote .Values.rpc.rpcPort }}
  LISTEN_PORT: {{ quote .Values.listenPort }}
  RPC_SECRET: {{ .Values.rpc.rpcSecret }}

kind: ConfigMap
metadata:
  creationTimestamp: "2021-12-22T02:13:16Z"
  name: aria2-configmap
  namespace: default
  resourceVersion: "823351"
  uid: {{ .Values.uid }}
