apiVersion: v1
kind: Service
metadata:
  name: youtube-dl-service
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.loadBalancerIP }}
  ports:
  - name: web
    port: 80
    targetPort: 8080
  selector:
    app: youtube-dl
