apiVersion: v1
kind: Service
metadata:
  name: calibre-service
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.loadBalancerIP }}
  ports:
  - name: web
    port: 80
    targetPort: 8083
  selector:
    app: calibre
