apiVersion: v1
kind: ConfigMap
metadata:
  name: frpc
  namespace: default
data:
  frpc.ini: |-
    [common]
    server_addr = {{ .Values.server.serverAddress }}
    server_port = {{ .Values.server.serverPort }}
    log_level = {{ .Values.logLevel }}
    token = {{ .Values.server.serverToken }}

    {{- range $name, $service := .Values.frpc.services }}
    [{{ $name }}]
    type = {{ $service.type }}
    sk = {{ $service.sk }}
    local_ip = {{ $service.localIP }}
    local_port = {{ $service.localPort }}
    {{- if $service.remotePort }}
    remote_port = {{ $service.remotePort }}
    {{- end }}
    {{- end }}

