apiVersion: v1
kind: ConfigMap
metadata:
  name: frpc
  namespace: default
data:
  frpc.toml: |-
    serverAddr = "{{ .Values.server.serverAddress }}"
    serverPort = {{ .Values.server.serverPort }}
    auth.token = "{{ .Values.server.serverToken }}"

    {{- range $name, $service := .Values.services }}
    [[ proxies ]]
    name = "{{ $name }}"
    type = "{{ $service.type }}"
    {{- if $service.sk }}
    secretKey = "{{ $service.sk }}"
    {{- end }}
    localIp = "{{ $service.localIP }}"
    localPort = {{ $service.localPort }}
    {{- if $service.remotePort }}
    remotePort = {{ $service.remotePort }}
    {{- end }}
    {{- end }}
