apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.loadBalancerIP }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 80
  selector:
    app: nginx
