- hosts: kubenodes
  gather_facts: yes
  become: yes
  roles:
    - role: k3s/prereq
    - role: k3s/download

- hosts: master
  become: yes
  roles:
    - role: k3s/master

- hosts: worker
  become: yes
  roles:
    - role: k3s/worker
