apiVersion: v1
kind: Service
metadata:
  name: kiwix-service
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.loadBalancerIP }}
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: kiwix
