apiVersion: apps/v1
kind: Deployment
metadata:
  name: artifactos
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: artifactos
  template:
    metadata:
      labels:
        app: artifactos
    spec:
      containers:
      - name: artifactos
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - name: http
          containerPort: 5000
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /etc/artifactos/config.yaml
          subPath: config.yaml
        - name: data
          mountPath: /data
      volumes:
      - name: config
        configMap:
          name: artifactos-config
          items:
          - key: config.yaml
            path: config.yaml
      - name: data
        nfs:
          server: {{ .Values.nfs.nfsMediaServerAddress }}
          path: {{ .Values.nfs.nfsDataMountPath}}
