apiVersion: v1
kind: Service
metadata:
  name: artifactos-service
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.loadBalancerIP }}
  ports:
  - name: http
    port: 80
    targetPort: 5000
  selector:
    app: artifactos
